from .model import Model
from .treatment import Treatment
from .patient import Patient
from .treatment_process import TreatmentProcess
from .medical_info_type import MedicalInfoType
from .medical_info_type_treatment_process_rel import MedicalInfoTypeTreatmentProcessRelation
from .medical_info import MedicalInfo
from .payment import Payment
from .health_expert import HealthExpert
